version: '3.8'
services:
  web:
    build: ./app
    command: python manage.py runserver 0.0.0.0:8000
    # command: python manage.py createsuperuser
    volumes:      
      - ./app/:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db

  db:
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - ./data:/var/lib/postgresql/data/
    ports:
      - 5432:5432